#Minecraft server properties
#Mon Jun 22 07:31:44 MSK 2026
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=normal
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=75
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=150
max-tick-time=100
max-world-size=29999984
motd=Enterra
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=10
prevent-proxy-connections=false
pvp=true
query.port=31363
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https\://www.dropbox.com/scl/fi/1z156b5rynk8ypz8typfl/JE-Vanilla-1.21-ResourcePack.zip?rlkey\=6y9771z2iu2qqckos96omgrb9&st\=dn8w0zvw&dl\=1
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=0.0.0.0
server-name=
server-port=31363
simulation-distance=4
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=6
white-list=false
